common_args:
  training_type: "cross_silo"
  random_seed: 0
  scenario: "horizontal"
  using_mlops: false
  config_version: release
  name: "org_bddGT_bddPD_bddVal_C1GT_C2GT_0.001LR" # yolo
  project: "runs/train" # yolo
  exist_ok: true # yolo

environment_args:
  bootstrap: ./config/bootstrap.sh

train_args:
  federated_optimizer: "FedAvg"
  client_id_list:
  client_num_in_total: 2
  client_num_per_round: 2
  comm_round: 500
  epochs: 1
  batch_size: 64
  client_optimizer: sgd
  lr: 0.01
  weight_decay: 0.0005
  checkpoint_interval: 1
  server_checkpoint_interval: 1

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 2
  using_gpu: true
  gpu_mapping_file: ./config/gpu_mapping_new.yaml
  gpu_mapping_key: mapping_config2_1_shoaib #mapping_config5_1_shoaib
  gpu_ids: [0,1,2,3,4,5,6,7]

comm_args:
  #backend: "MPI"
  #is_mobile: 0
  backend: "GRPC"
  grpc_ipconfig_path: config/grpc_ipconfig.csv
  #backend: "MQTT_S3"
  #mqtt_config_path: ./config/mqtt_config.yaml
  #s3_config_path: ./config/s3_config.yaml

tracking_args:
  log_file_dir: ./log
  enable_wandb: true
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_torch_object_detection


data_args:
  dataset: "bdd"
  data_cache_dir: ./fedcv_data
  partition_method: "homo"
  partition_alpha: 0.5
  data_conf: "./data/bdd.yaml" # yolo
  img_size: [640, 640] # [640, 640]


model_args:
  model: "yolov5" # "yolov5"
  class_num: 13
  yolo_cfg: "./model/yolov5/models/yolov5s.yaml" # "./model/yolov6/configs/yolov6s.py" # yolo
  yolo_hyp: "./config/hyps/hyp.scratch.yaml" # yolo
  yolo_opt: "./runs/train/opt.yaml"
  weights: "none" #"/home/shoaib/FedML_MSIS_Shoaib/python/app/fedcv/object_detection/runs/train/org_bddGT_bddPD_bddVal_C1PD_C2Rec_working/weights/model_client_2_round_118.pt" #"none" #"/home/shoaib/FedML_MSIS_Shoaib/python/app/fedcv/object_detection/runs/train/org_bddGT_bddPD_bddVal/weights/model_client_2_round_128.pt" #'best.pt' #'/home/shoaib/FedML_MSIS_Shoaib/python/app/fedcv/object_detection/runs/train/Exp0/weights/aggr_model_198.pt' #'/home/shoaib/FedML_MSIS_Shoaib/python/app/fedcv/object_detection/runs/train/3class_bddGT_bddPD/weights/aggr_model_131.pt' #"/home/gpuadmin/Project/FedML_MSIS_Shoaib/python/app/fedcv/object_detection/best.pt" #"none" # "best.pt" # yolo
  single_cls: false # yolo
  conf_thres: 0.001 # yolo
  iou_thres: 0.6 # for yolo NMS
  yolo_verbose: true # yolo


new_data_args:
  new_data: "bdd"
  new_data_conf: "./data/bdd_full.yaml" # yolo
  new_data_num_images: 5000
  new_data_min_rounds: -1
  min_map_for_pseudo_generation: 0.2

  use_new_data: False # False to use only original data from server
  use_new_data_pseudos: True # False to disable pseudo label generation
  use_new_data_recover: True # False to disable pseudo label recovery

  tmp_merge_file: "../../../../merged_list.txt"
  tmp_gt_files: "../../../../tmp.txt"
  new_deepsort_config: "Yolov5_DeepSORT_PseudoLabels/deep_sort/configs/deep_sort.yaml"
  conf_thresh_low: 0.01 # Low confidence threshold for pseudo labels
  conf_thresh_high: 0.5 # High confidence threshold for pseudo labels
  conf_thres: 0.5
  iou_thres: 0.6
  psuedo_generate_clients: [1,3,5,7]
  psuedo_recovery_on_clients: [2,4,6,8]
  color_str: "bright_yellow" #bright_red, bright_green, bright_blue

  run_name: "Org_BDDTrain_BDDVal_New5kBDD_CGT_C2GT___0_001LR"