common_args:
  training_type: "cross_silo"
  random_seed: 0
  scenario: "horizontal"
  using_mlops: false
  config_version: release
  name: "Exp1" # yolo
  project: "runs/train" # yolo
  exist_ok: true # yolo

environment_args:
  bootstrap: ./config/bootstrap.sh


data_args:
  dataset: "bdd"
  data_cache_dir: ./fedcv_data
  partition_method: "homo"
  partition_alpha: 0.5
  data_conf: "./data/bdd.yaml" # yolo
  img_size: [640, 640] # [640, 640]

model_args:
  model: "yolov5" # "yolov5"
  class_num: 13
  yolo_cfg: "./model/yolov5/models/yolov5s.yaml" # "./model/yolov6/configs/yolov6s.py" # yolo
  yolo_hyp: "./config/hyps/hyp.scratch.yaml" # yolo
  yolo_opt: "./runs/train/opt.yaml"
  weights: 'none' #"/home/gpuadmin/Project/FedML_MSIS_Shoaib/python/app/fedcv/object_detection/best.pt" #"none" # "best.pt" # yolo
  single_cls: false # yolo
  conf_thres: 0.001 # yolo
  iou_thres: 0.6 # for yolo NMS
  yolo_verbose: true # yolo

train_args:
  federated_optimizer: "FedAvg"
  client_id_list:
  client_num_in_total: 4
  client_num_per_round: 4
  comm_round: 300
  epochs: 1
  batch_size: 64
  client_optimizer: sgd
  lr: 0.01
  weight_decay: 0.0005
  checkpoint_interval: 1
  server_checkpoint_interval: 1

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 4
  using_gpu: true
  gpu_mapping_file: ./config/gpu_mapping_new.yaml
  gpu_mapping_key: mapping_config4_1
  gpu_ids: [0,1,2,3,4,5,6,7]

comm_args:
  #backend: "MPI"
  #is_mobile: 0
  backend: "GRPC"
  grpc_ipconfig_path: config/grpc_ipconfig.csv
  #backend: "MQTT_S3"
  #mqtt_config_path: ./config/mqtt_config.yaml
  #s3_config_path: ./config/s3_config.yaml

tracking_args:
  log_file_dir: ./log
  enable_wandb: true
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_torch_object_detection
